### ISSUE TITLE
Add possibility to hide/disable “agreement” checkbox

### ISSUE THREAD

**Issue by coditive-mariola-wp** [wpserved/simple-floating-contact-form#1]
There should be possibility to hide or disable the "agreement" checkbox from plugin's settings page

**Comment by coditive-mariola-wp** [comment]
Add a note in ReadMe about the possibility to hide or disable after work on the task.

**Comment by coditive-michal-k** [comment]
It's done. Now we can disable this form field if we leave it empty in wp admin
